### ISSUE TITLE
24.07 Release

### ISSUE THREAD

**Issue by Sean-StarLabs** [StarLabsLtd/firmware#184]
## StarLite
- [ ] Closes #183:  eMMC Scan
- [ ] Closes #182: Tell the OS keyboard is internal
- [ ] Closes #175 : Intermittent touchscreen
- [ ] Closes #180 : Bluetooth scanning

For anyone wanting to try the latest build, changes are:
* Adjust the charging frequency to improve stability
* Change the touchscreen IRQ to driver to improve stability
* Add an option to disable waking from suspend by opening the lid
* Change the default power profile to balanced
* Adjust the memory training
* Adjust the Hot Plug Detection for the USB-C ports
* Optimise GPIO configuration
* Initialise the wireless card later in the boot process
* Add an option to limit the charging current
* Tweaks the timing of the power button
* Optimise how the temperature is read from the battery
* Wait for an RDO when starting from G3
* Speed up CC
* Remove superfluous CFR options
* Improve ACPI for CNVi
* Report tablet "docked" status

To install:

First, install flashrom:
Ubuntu:
```
sudo apt install flashrom
```
Fedora
```
sudo dnf install flashrom
```
Arch
```
sudo pacman -Syyuu flashrom
```

Then, connect your charger and run:

```
wget https://github.com/StarLabsLtd/firmware/raw/master/StarLite/MkV/coreboot/24.07/24.07.rom
sudo flashrom -p internal -w 24.07.rom -i bios --ifd -n -N
sudo shutdown now
```
Once that has finished, please shutdown (not reboot), **disconnect the charger**, and wait for 12 seconds until you see the LEDs flicker. Once that happens, you can reconnect the charger and continue.

If you see a message Message recipient disconnected from message bus without replying or /dev/mem mmap failed: Operation not permitted, you'll need to add the iomem=relaxed kernel parameter. The two below commands will do this for you:

```
sudo sed -i 's/quiet/quiet iomem=relaxed/g' /etc/default/grub
sudo update-grub
```

**Comment by clhodapp** [comment]
I used `flashrom` to flash version 24.06 on my StarLite Mk V, and was able to see the version update in `/sys/class/dmi/id/ec_firmware_release`. However, after following the same procedure with this 24.07 daily build, I'm still seeing 24.06 in `/sys/class/dmi/id/ec_firmware_release` and actually 24.05 in `/sys/class/dmi/id/bios_release`.

Is this expected, and 24.07 just hasn't had its baked-in version string updated? Or did something go wrong with my flashing?

**Comment by PhilT** [comment]
^^ Description links to issue 182 twice.

**Comment by thmichel** [comment]
Installed the update. Seems #182 isn't fixed, if I remove the quirks file the keyboard is not recognized as internal. Also I have a frequent screen flicker after the upgrade.

**Comment by Sean-StarLabs** [comment]
> Is this expected

Yes

> Installed the update. Seems https://github.com/StarLabsLtd/firmware/issues/182 isn't fixed

Haven't made any changes yet for #182 

> ^^ Description links to issue 182 twice.

Done

**Comment by dev-da77** [comment]
My StarLabe Lite 5 runs EndeavourOS (Archlnux).
flashrom is installed.

I executed

`sudo flashrom -p internal -w <filename>.rom -i bios --ifd -n -N`

with 24.06.rom and 240710.rom

and received:

```
flashrom v1.3.0 on Linux 6.9.8-arch1-1 (x86_64)
flashrom is free software, get the source code at https://flashrom.org

Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Opened /dev/mtd0 successfully
Found Programmer flash chip "Opaque flash chip" (16384 kB, Programmer-specific) on internal.
Reading ich descriptor... done.
Using region: "bios".
Error: Image size (292660 B) doesn't match the expected size (16777216 B)!

```

So I can not update from 24.5 to one of the newer versions.

My SSD in encrypted, if this is from interest.

**Comment by Sean-StarLabs** [comment]
Whatever the file is that you're trying to flash, it's too big to fit on the chip

**Comment by dev-da77** [comment]
First try: I downloaded with the wrong path (file size: 168,1 KB):

`https://github.com/StarLabsLtd/firmware/blob/master/StarLite/MkV/coreboot/24.06/24.06.rom`

Correct path is (file size: 16,8 MB):

`https://github.com/StarLabsLtd/firmware/raw/master/StarLite/MkV/coreboot/24.06/24.06.rom`

Than I could update to 24.6

**Comment by rogercreagh** [comment]
Trying to do 24.07 on Ubuntu 24.04

flashrom already installed from previous update to 24.06

`wget https://github.com/StarLabsLtd/firmware/raw/master/StarLite/MkV/coreboot/Daily%20Builds/240710.rom` appeared to work ok.  File  240710.rom has arrived with size 16777216 bytes

then running  `sudo flashrom -p internal -w coreboot.rom -i bios --ifd -n -N`
generated this output:

```
$ sudo flashrom -p internal -w coreboot.rom -i bios --ifd -n -N
[sudo] password for roger: 
flashrom 1.4.0-devel on Linux 6.8.0-36-generic (x86_64)
flashrom is free software, get the source code at https://flashrom.org

Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Cannot open file stream for /dev/mtd0
coreboot table found at 0x7689f000.
Found chipset "Intel Alder Lake-N".
Enabling flash write... Warning: Setting BIOS Control at 0xdc from 0x8b to 0x89 failed.
New value is 0x8b.
SPI Configuration is locked down.
FREG0: Flash Descriptor region (0x00000000-0x00000fff) is read-only.
FREG1: BIOS region (0x00600000-0x00ffffff) is read-write.
FREG2: Management Engine region (0x00001000-0x00412fff) is locked.
Not all flash regions are freely accessible by flashrom. This is most likely
due to an active ME. Please see https://flashrom.org/ME for details.
At least some flash regions are read protected. You have to use a flash
layout and include only accessible regions. For write operations, you'll
additionally need the --noverify-all switch. See manpage for more details.
OK.
Unable to identify chip, mfg_id: 0xa1, model_id: 0x2818
Found Programmer flash chip "Opaque flash chip" (16384 kB, Programmer-specific) on internal.
Reading ich descriptor... done.
Using region: "bios".
Error: opening file "coreboot.rom" failed: No such file or directory
```
why is it looking for coreboot.rom when no such file was downloaded. Should the command be:
`sudo flashrom -p internal -w 240710.rom -i bios --ifd -n -N`
or the wget be:
`wget https://github.com/StarLabsLtd/firmware/raw/master/StarLite/MkV/coreboot/Daily%20Builds/coreboot.rom`

??? or something else???  - rename 240710.rom to coreboot.rom?  Also what's all that stuff about read-only and locked regions - I dont remember seeing that when going to 24.06 (but maybe I did?)

**Comment by Sean-StarLabs** [comment]
Instructions updated

**Comment by altatechor** [comment]
did not get errors during the flashing process. but now I cannot boot anymore, always drop into the UEFI shell. Any tips?

**Comment by Sean-StarLabs** [comment]
Most likely the Boot Entry wasn't created automatically - what distro are you using?

Most distros can be started with this (replace ubuntu with whatever you're using):
```
fs0:
cd EFI
cd ubuntu
grubx64.efi
```

**Comment by altatechor** [comment]
Your help already reached me indirectly [via](https://reddit.com/comments/1e2mmg2/comment/ld4cnuu) someone else you helped, thx!

**Comment by vdessotti** [comment]
Hello

When I try the flashrom command it gives me:
`Warning: No chipset found. Flash detection will most likely fail`

I did update to 24.06 before and it went fine.

Thanks,

**Comment by Sean-StarLabs** [comment]
Need more info, full output, version, distro

**Comment by tobbsn** [comment]
I did this upgrade successfully. At least I think so, since most problems I had with `24.6` seem to be gone now. But both `/sys/class/dmi/id/bios_version` and `/sys/class/dmi/id/ec_firmware_release` still return the old `24.06` and `24.6`. Is it possible that I am actually still running the old firmware?

**Comment by Sean-StarLabs** [comment]
Unlikely, but you can check the build date to be sure

**Comment by vdessotti** [comment]
Hello,

I am on Zorin OS 17.1 Core
Kernel is 6.5.0-44-generic
24.06 update went fine. 

I am trying to update for 24.07 but it gives this error:

```
flashrom` v1.2 on Linux 6.5.0-44-generic (x86_64)
flashrom is free software, get the source code at https://flashrom.org

Using clock_gettime for delay loops (clk_id: 1, resolution: 1ns).
Cannot open file stream for /dev/mtd0
coreboot table found at 0x7689f000.
WARNING: No chipset found. Flash detection will most likely fail.
========================================================================
You may be running flashrom on an unknown laptop. We could not
detect this for sure because your vendor has not set up the SMBIOS
tables correctly. Some internal buses have been disabled for
safety reasons. You can enforce using all buses by adding
  -p internal:laptop=this_is_not_a_laptop
to the command line, but please read the following warning if you
are not sure.

Laptops, notebooks and netbooks are difficult to support and we
recommend to use the vendor flashing utility. The embedded controller
(EC) in these machines often interacts badly with flashing.
See the manpage and https://flashrom.org/Laptops for details.

If flash is shared with the EC, erase is guaranteed to brick your laptop
and write may brick your laptop.
Read and probe may irritate your EC and cause fan failure, backlight
failure and sudden poweroff.
You have been warned.
========================================================================
No EEPROM/flash device found.
Note: flashrom can never write if the flash chip isn't found automatically.
```


Thanks,

**Comment by dev-da77** [comment]
@Sean-StarLabs : Can you provide a change list for 240725.rom?

**Comment by dev-da77** [comment]
My device is only charging, when shutdown.
If it is in standby, it is not charging.
If it is running, it is discharging, while it is plugged-in.

**Comment by Sean-StarLabs** [comment]
> Can you provide a change log for 240725.rom?

As above

> not charging.

No charge LED?

**Comment by dev-da77** [comment]
When I plug in the USB cable, the LED is constant red (not blinking) - independent if device is running, standby or shotdown. Gnome battery icon is also showing, that it should charge. But percentage value is counting down.

**Comment by Sean-StarLabs** [comment]
What percentage range? Centre of the battery icon in GNOME - is it green or white?

**Comment by dev-da77** [comment]
Battery icon is white.

![grafik](https://github.com/user-attachments/assets/7e6b7668-de43-4240-b9bf-ef7c9870f15d)

**Comment by dev-da77** [comment]
gnome-power-manager:

![grafik](https://github.com/user-attachments/assets/0968ca7f-c79d-45c1-9df5-6c927cae85f1)

**Comment by dev-da77** [comment]
Nevertheless it is discharging. Now it is at 80%.

**Comment by Sean-StarLabs** [comment]
> Battery icon is white.

That means charged connected, not charging.

Stays at 80%??

**Comment by dev-da77** [comment]
No, it don't stay.

Charge-USB is connected
Charge-LED is red
Gnome battery icon shows, it is charging
Gnome-power-manager shows it is charging

BUT charge value is going down, not up like expected.

At coreboot, charge speed is 0,5

**Comment by Sean-StarLabs** [comment]
Presumably, if you flash the previous build, it will charge again?

**Comment by dev-da77** [comment]
I'm back on version 24.06 and charging works again.

With 240719 I had the same charging issue like with the newest version 240725, before and after downgrade. Than I downgraded to 240705, but my display flickered. Now I'm back to 24.06. Seams to be working better for me.

**Comment by echo-devnull** [comment]
It could be me (probably is) but how does one make use of this "`Add an option to disable waking from suspend by opening the lid`"  feature? ]

I cannot seem to find it in the coreboot menu. (I do see thee "`Adjust the charging frequency to improve stability`" option though and I see that `24.07` is the latest version)

**Comment by echo-devnull** [comment]
> Not you, set to off at the moment waiting to see if anyone says anything :)

Ah allright then.   I won't say a thing.

**Comment by JamesOsborn-SE** [comment]
> I used `flashrom` to flash version 24.06 on my StarLite Mk V, and was able to see the version update in `/sys/class/dmi/id/ec_firmware_release`. However, after following the same procedure with this 24.07 daily build, I'm still seeing 24.06 in `/sys/class/dmi/id/ec_firmware_release` and actually 24.05 in `/sys/class/dmi/id/bios_release`.
> 
> Is this expected, and 24.07 just hasn't had its baked-in version string updated? Or did something go wrong with my flashing?

If you run the command below, you can see the version like so:
```
SMBIOS BiosVendor=coreboot
SMBIOS BiosVersion=24.07
```

```shell
sudo fwupdtool get-devices --plugins flashrom --verbose
```

**Comment by tomellis** [comment]
Not sure if it's just me but after installing this the screen rotation is now incorrect again. I am using the [workaround described on the starlabs support page](https://support.starlabs.systems/kb/guides/starlite-fixing-rotation-on-older-kernel) but after firmware upgrade I'm back to the wrong orientation. After installing the gnome-shell screen rotation add-on I can get the screen around the right way ([as per reddit](https://www.reddit.com/r/starlabs_computers/comments/1dyebde/starlite_mkv_autorotate_solution/)).

I know it's mentioned this is a symptom of older kernels and fixed upstream but which version fixes it?
I've tried newer [vanilla kernel builds](https://fedoraproject.org/wiki/Kernel_Vanilla_Repositories) in Fedora Silverblue but those didn't seem to include the fix. Default Fedora Silverblue kernel is currently 6.9.11-200.fc40.

**Comment by Sean-StarLabs** [comment]
The commands in the support article should be all needed if the kernel doesn't support it. Whether the kernel supports it differs depending on the build (patch was upstreamed into 6.8).

Only other things that's known to cause issues is having an entry in /usr/lib/udev/hwdb.d/60-sensor.hwdb for the StarLite - but AFAIK, no distro has that in it.
